//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeStokcs.DLL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid InwardId { get; set; }
        public System.Guid SockItemId { get; set; }
        public int Qunatity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual StockItem StockItem { get; set; }
        public virtual User User { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
